spring:
  application:
    name: rest-api
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    show-sql: true